version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - app-network
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: bitnami/mysql:8.0
    container_name: mysql
    networks:
      - app-network
    volumes:
      - db-data:/bitnami/mysql/data
    ports:
      - '3308:3306'
    environment:
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ./wordpress
      o: bind
  db:
    driver: local
    driver_opts:
      type: none
      device: ./db-data
      o: bind