version: '3.7'

services:
  mysqld_exporter:
    image: prom/mysqld-exporter:v0.15.0
    command:
      - '--config.my-cnf=""'
      - '--mysqld.username=exporter'
      - '--mysqld.password=exporterpassword'
      - '--mysqld.address=127.0.0.1:3306'
    network_mode: host
    restart: unless-stopped
