version: '3.7'

services:
  mysqld_exporter:
    image: quay.io/prometheus/mysqld-exporter
    container_name: mysqld-exporter
    command:
      - "--mysqld.username=exporter:exporterpassword"
      - "--mysqld.address=127.0.0.1:3306"
    network_mode: host
    restart: unless-stopped
